# Generated by Django 4.2.5 on 2023-10-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ImageField(blank=True, upload_to='image/%Y/%m/%d')),
                ('image', models.CharField(max_length=20, verbose_name='Фио')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20, verbose_name='Фио'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
