# Generated by Django 4.2.5 on 2023-10-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ment_remove_post_description_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ment',
            new_name='Mentor',
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'New blog for mentor'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'New blog'},
        ),
    ]
