# Generated by Django 4.2.5 on 2023-10-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_ment_mentor_alter_mentor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название для вашей статьи')),
                ('main', models.CharField(max_length=300, verbose_name='Для вашей статьи')),
            ],
            options={
                'verbose_name': 'New state',
            },
        ),
    ]
