# Generated by Django 4.2.5 on 2023-10-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='image',
            new_name='image1',
        ),
    ]
